image: edbizarro/gitlab-ci-pipeline-php:7.2

stages:
  - building
  - testing
  - security

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: building
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - composer.lock
      - vendor/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

phpunit:
  stage: testing
  dependencies:
    - composer
  script:
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak
    - echo "" | sudo tee /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - ./vendor/phpunit/phpunit/phpunit --version
    - php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit -v --colors=never --stderr
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

codestyle:
  stage: testing
  script:
    - test -f phpcs.phar || curl -L https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar -o phpcs.phar
    - php phpcs.phar --extensions=php --standard=PSR2 src
  dependencies: []
  cache:
    paths:
      - phpcs.phar

psalm:
  stage: testing
  dependencies:
    - composer
  script:
    - cp psalm.xml.dist psalm.xml
    - ./vendor/vimeo/psalm/psalm --version
    - ./vendor/vimeo/psalm/psalm

phpcpd:
  stage: testing
  dependencies: []
  script:
    - test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
    - php phpcpd.phar src/ --min-lines=50
  cache:
    paths:
      - phpcpd.phar

sensiolabs:
  stage: security
  dependencies:
    - composer
  script:
    - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
    - cd security-checker
    - composer install
    - php security-checker security:check ../composer.lock
  cache:
    paths:
      - security-checker/
